"リレーション課題完了"
Yugenn/Yugenn_app pull request #1
Opened 2021-10-04 13:24 UTC by Yugenn

## アプリのタイトル
Yugenn_人間登録アプリ

## アプリの概要
出会った人を忘れないように顔と特徴を把握するためのアプリです。

## 画面のスクリーンショット
<img width="1280" alt="スクリーンショット 2021-10-04 22 03 39" src="https://user-images.githubusercontent.com/89439437/135858828-36216043-4d43-4634-8ada-b30946256604.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 07 53" src="https://user-images.githubusercontent.com/89439437/135858863-a9674f2f-bded-4c69-bd0b-77637b59e853.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 08 01" src="https://user-images.githubusercontent.com/89439437/135858891-9da3f961-12b9-4e75-8a3b-622b163031ef.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 08 09" src="https://user-images.githubusercontent.com/89439437/135858906-9d4e0138-14ea-408d-aeaf-79bc3268224c.png">

2021-10-04 13:27 UTC, Yugenn commented
スクリーンショットを間違えたのでもう一度贈ります
<img width="1280" alt="スクリーンショット 2021-10-04 22 03 39" src="https://user-images.githubusercontent.com/89439437/135859479-739d415f-6047-4261-9f05-21240a17f2ac.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 08 01" src="https://user-images.githubusercontent.com/89439437/135859513-d24d7416-a3b9-4a2f-a49b-4a8a2e41834c.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 08 09" src="https://user-images.githubusercontent.com/89439437/135859522-de736d0b-493d-4a9c-a3ea-e0bc596cc0e7.png">
<img width="1280" alt="スクリーンショット 2021-10-04 22 08 23" src="https://user-images.githubusercontent.com/89439437/135859529-ec9f9c2e-85e9-4ffd-b4c6-4e045d63273a.png">

2021-10-04 13:41 UTC, Yugenn commented
Admin登録画面
<img width="1280" alt="スクリーンショット 2021-10-04 22 40 15" src="https://user-images.githubusercontent.com/89439437/135861825-40dc6e97-2e6b-4545-99d3-f156b6f93e2d.png">

2021-10-04 14:32 UTC, kazu-taka requested changes
@Yugenn 
Slackにも記述しましたが、ArticleのCRUD処理ができていないようなので、CRUD処理の実装をお願いします:bow:
画像についてはSlackをご確認願います！
https://spartacamp.slack.com/archives/C02BZB580F5/p1633357783181100

2021-10-04 14:32 UTC, kazu-taka commented on resources/views/articles/show.blade.php
> +        <colgroup span="1" style="width:200px;background-color:#efefef;"></colgroup>
@Yugenn 
本当であれば、cssファイルに書いて欲しいですが今回はOKです！！

2021-10-07 03:49 UTC, Yugenn commented
オリジナルアプリ完了しました。
詳細はREADMEに記載しております。

2021-10-07 04:10 UTC, kazu-taka approved these changes
@Yugenn 
1箇所修正して頂けたらマージしてOKです！！

2021-10-07 04:10 UTC, kazu-taka commented on resources/views/articles/show.blade.php
> +                </div>
@Yugenn 
インデントしすぎちゃってます^^;

2021-10-07 09:12 UTC, merged